NUM_EPOCHS: 15
WARMUP_STEPS_FRAC: 0.15
STEPS_BETWEEN_EVAL: 500
GRAD_ACCUM_STEPS: 3
SAVE_CHECKPOINT_STEPS: 1500
LR: 1e-6
WEIGHT_DECAY: 0.0001
TRAIN_BATCH_SIZE: 5
VALIDATION_BATCH_SIZE: 3
HEAD_SUM_BIAS_ENABLED: True
TRAIN_EFFECTIVE_BATCH_SIZE: ${oc.decode:${GRAD_ACCUM_STEPS}} * ${oc.decode:${TRAIN_BATCH_SIZE}}