
BLIP_VARIANT: base # "base" | "large"
NUM_EPOCHS: 3
WARMUP_STEPS_FRAC: 0.15
STEPS_BETWEEN_EVAL: 100
GRAD_ACCUM_STEPS: 15
SAVE_CHECKPOINT_STEPS: 100
LR: 5e-6
WEIGHT_DECAY: 0.001
TRAIN_BATCH_SIZE: 1
VALIDATION_BATCH_SIZE: 3
HEAD_SUM_BIAS_ENABLED: True
TRAIN_EFFECTIVE_BATCH_SIZE: ${oc.decode:${GRAD_ACCUM_STEPS}} * ${oc.decode:${TRAIN_BATCH_SIZE}}