
BLIP_VARIANT: base # "base" | "large"
NUM_EPOCHS: 6
WARMUP_STEPS_FRAC: 0.1
STEPS_BETWEEN_EVAL: 500
GRAD_ACCUM_STEPS: 1
SAVE_CHECKPOINT_STEPS: 500
LR: 5e-6
WEIGHT_DECAY: 0.001
TRAIN_BATCH_SIZE: 3
VALIDATION_BATCH_SIZE: 3
HEAD_SUM_BIAS_ENABLED: True
TRAIN_EFFECTIVE_BATCH_SIZE: ${oc.decode:${GRAD_ACCUM_STEPS}} * ${oc.decode:${TRAIN_BATCH_SIZE}}